import { userTable } from './users.schema';
import { userRolesTable } from './userRoles.schema';
import { postsTable } from './posts.schema';
import { commentsTable } from './comments.schema';
import { countries } from './countries.schema';
import { CountryCode } from './country-code.schema';
import { otp } from './otp.schema';
import { oauthTable } from './oauth.schema';
import { postCategoriesTable } from './post-categories.schema';
